-- Baseline schema, dumped from the local dev DB (Hibernate ddl-auto: update history) via
-- `pg_dump --schema-only`. Kept close to the dump so it matches the current dev schema exactly;
-- future schema changes belong in new versioned migrations, not edits to this file.

CREATE TABLE attractions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    address character varying(255) NOT NULL,
    content_id character varying(255) NOT NULL,
    content_type_id character varying(255) NOT NULL,
    description character varying(255),
    image_url character varying(255),
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    region_id bigint,
    synced_at timestamp(6) without time zone NOT NULL,
    title character varying(255) NOT NULL,
    CONSTRAINT uk3rw3rcob4p1552ejr96h5by81 UNIQUE (content_id)
);

CREATE TABLE badges (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    code character varying(255) NOT NULL,
    description character varying(255),
    icon_url character varying(255),
    name character varying(255) NOT NULL,
    required_visit_count integer NOT NULL,
    CONSTRAINT uk3uvqm0wd6pysfcyv49hp7mroy UNIQUE (code)
);

CREATE TABLE characters (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    description character varying(255),
    image_url character varying(255),
    name character varying(255) NOT NULL,
    region_id bigint NOT NULL,
    CONSTRAINT uk8rrpvsa3xsaw61thg8egl6472 UNIQUE (region_id)
);

CREATE TABLE items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    category character varying(20) NOT NULL,
    description character varying(255),
    image_url character varying(500),
    name character varying(100) NOT NULL,
    price integer NOT NULL,
    CONSTRAINT items_category_check CHECK (((category)::text = ANY ((ARRAY['GLASSES'::character varying, 'BAG'::character varying, 'CARRIER'::character varying, 'HAT'::character varying])::text[])))
);

CREATE TABLE point_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    balance integer NOT NULL,
    user_id bigint NOT NULL,
    version bigint NOT NULL,
    CONSTRAINT ukhgx8ob2ypyfx47rhajdofl2hb UNIQUE (user_id)
);

CREATE TABLE point_histories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    amount integer NOT NULL,
    balance_after integer NOT NULL,
    reason character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT point_histories_reason_check CHECK (((reason)::text = ANY ((ARRAY['CHARACTER_COLLECT'::character varying, 'PRODUCT_COLLECT'::character varying, 'SHOP_PURCHASE'::character varying, 'ADMIN_ADJUST'::character varying, 'OTHER'::character varying])::text[])))
);

CREATE TABLE refresh_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    expires_at timestamp(6) without time zone NOT NULL,
    token character varying(512) NOT NULL,
    user_id bigint NOT NULL,
    token_hash character varying(512) NOT NULL
);

CREATE TABLE regions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    name character varying(255) NOT NULL,
    sigungu_code character varying(255) NOT NULL,
    verification_radius_meters integer NOT NULL
);

CREATE TABLE tour_api_region_mappings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    region_id bigint NOT NULL,
    tour_api_area_code character varying(255) NOT NULL,
    tour_api_sigungu_code character varying(255),
    CONSTRAINT uk4s2iubfnepr78d4pojnjt7kjv UNIQUE (region_id)
);

CREATE TABLE travel_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    content text NOT NULL,
    image_url character varying(500),
    place_name character varying(200) NOT NULL,
    title character varying(100) NOT NULL,
    user_id bigint NOT NULL,
    visited_at date NOT NULL
);

CREATE TABLE user_badges (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    acquired_at timestamp(6) without time zone NOT NULL,
    badge_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT uk5r2v5xn0il3p8dc9nf4v94r2b UNIQUE (user_id, badge_id)
);

CREATE TABLE user_characters (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    acquired_at timestamp(6) without time zone NOT NULL,
    character_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT ukaaincys5lsa8o4p12i4tyglty UNIQUE (user_id, character_id)
);

CREATE TABLE user_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_equipped boolean NOT NULL,
    item_id bigint NOT NULL,
    purchased_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT ukt1fm75442g6mqcekt9ojereou UNIQUE (user_id, item_id)
);

CREATE TABLE user_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    notification_enabled boolean NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT uk4bos7satl9xeqd18frfeqg6tt UNIQUE (user_id)
);

CREATE TABLE user_visit_counters (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    version bigint NOT NULL,
    visit_count integer NOT NULL,
    CONSTRAINT uk5fut2k8fa796ftom4s37oe72a UNIQUE (user_id)
);

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    email character varying(255),
    nickname character varying(255),
    profile_image_url character varying(255),
    provider character varying(255) NOT NULL,
    provider_id character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    withdrawn_at timestamp(6) without time zone,
    CONSTRAINT users_provider_check CHECK (((provider)::text = ANY ((ARRAY['GOOGLE'::character varying, 'KAKAO'::character varying, 'NAVER'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'WITHDRAWN'::character varying])::text[]))),
    CONSTRAINT ukcbysvpk95086ud4n4g6mkspai UNIQUE (provider, provider_id)
);

CREATE TABLE visit_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    region_id bigint NOT NULL,
    user_id bigint NOT NULL,
    visited_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT ukim775c4rln0mehkm1cr7eqtw2 UNIQUE (user_id, region_id)
);
