-- docs/ISSUE-여행기록-스키마확장.md: 여행 기록에 사진(별도 테이블)/좌표/날씨/기분/즐겨찾기 지원

ALTER TABLE travel_records DROP COLUMN image_url;

ALTER TABLE travel_records ADD COLUMN latitude double precision;
ALTER TABLE travel_records ADD COLUMN longitude double precision;
ALTER TABLE travel_records ADD COLUMN weather character varying(20);
ALTER TABLE travel_records ADD COLUMN temperature integer;
ALTER TABLE travel_records ADD COLUMN mood character varying(20);
ALTER TABLE travel_records ADD COLUMN favorited_at timestamp(6) without time zone;

-- 신규 컬럼이라 기존 데이터가 없다는 전제로 바로 NOT NULL 적용.
-- 운영 데이터가 이미 있는 시점에 이 마이그레이션을 적용한다면 백필 후 적용해야 한다.
ALTER TABLE travel_records ALTER COLUMN latitude SET NOT NULL;
ALTER TABLE travel_records ALTER COLUMN longitude SET NOT NULL;
ALTER TABLE travel_records ALTER COLUMN weather SET NOT NULL;
ALTER TABLE travel_records ALTER COLUMN temperature SET NOT NULL;
ALTER TABLE travel_records ALTER COLUMN mood SET NOT NULL;

ALTER TABLE travel_records ADD CONSTRAINT travel_records_weather_check
    CHECK (((weather)::text = ANY ((ARRAY['CLEAR'::character varying, 'SNOW'::character varying, 'RAIN'::character varying, 'THUNDER'::character varying, 'WIND'::character varying, 'CLOUDY'::character varying])::text[])));

ALTER TABLE travel_records ADD CONSTRAINT travel_records_mood_check
    CHECK (((mood)::text = ANY ((ARRAY['EXCITED'::character varying, 'HAPPY'::character varying, 'NEUTRAL'::character varying, 'SAD'::character varying, 'DISTRESSED'::character varying])::text[])));

CREATE TABLE record_images (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    record_id bigint NOT NULL,
    image_url character varying(500) NOT NULL,
    sort_order integer NOT NULL
);

CREATE INDEX idx_record_images_record_id ON record_images (record_id);
